### ISSUE TITLE
ChatterBot Cannot think?

### ISSUE THREAD

**Issue by ItzSomebody** [tavonkelly/ChatterBot#1]
Using PaperSpigot 1.8.8

[00:42:33 WARN]: [ChatterBot] ChatterBot could not think: http://www.cleverbot.com/webservicemin?uc=321
[00:42:33 WARN]: Exception in thread "Craft Scheduler Thread - 2670"
[00:42:33 WARN]: org.apache.commons.lang.UnhandledException: Plugin ChatterBot v1.8.5 generated an exception while executing task 1004907
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException

**Comment by tavonkelly** [comment]
Fixed with commit https://github.com/tavonkelly/ChatterBot/commit/c083868ed8b789c5176973faf1a5f86830ba84f6. Check for the latest jar on Spigot http://www.spigotmc.org/resources/chatterbot.890/

**Comment by ItzSomebody** [comment]
The "Latest" jar is actually 1.8.5

**Comment by tavonkelly** [comment]
Sorry. It's fixed now, thanks.
